[package]
name = "boxscript"
version = "0.1.0"
authors = ["pyxiis <47072520+pyxiis@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/boxscript/boxscript-rs"
publish = false

[dependencies]
